layout_spectrum: 0.25562783936038613
typography_spectrum: 0.899626427097246
color:
  brandStrength: 0.08237447729334235
  lightness: 0.3234975538216531
  saturation: 0.48116913880221546
  rhythmicContrast: 0.3207805473357439
  brandColors:
    - '#A7304F'
    - '#F46D8D'
    - '#F39EB5'
    - '#081028'
    - '#F0CEB7'
author:
  name: Design Bordello
  email: mail@designbordello.com
  url: 'http://www.designbordello.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0a669c24-3227-4e14-a189-d4f5edf6307c.jpg
name: Design Bordello
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/16a2221a-7bb3-4df5-8464-02565757a13b.png
title: Design for Agreeable Humans
description: Designing for Agreeable Humans
