typography_spectrum: 0.6549271321855485
color:
  brandStrength: 0.3595679469872266
  lightness: 0.012820534175261855
  saturation: 0.19634226593188941
  rhythmicContrast: 0.9206758379004896
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.3895037970505655
author:
  name: Design Bordello
  email: mail@designbordello.com
  url: 'http://www.designbordello.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0a669c24-3227-4e14-a189-d4f5edf6307c.jpg
name: Design Bordello
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/16a2221a-7bb3-4df5-8464-02565757a13b.png
title: Design for Agreeable Humans
description: Designing for Agreeable Humans
